# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'summary.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslationSummary(object):
    def setupUi(self, TranslationSummary):
        TranslationSummary.setObjectName("TranslationSummary")
        TranslationSummary.resize(1125, 1037)
        TranslationSummary.setStyleSheet("QWidget {\n"
"    background-color: #83A2FF;\n"
"    color: #FFFFFF;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TranslationSummary)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, 50, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.score_label = QtWidgets.QLabel(TranslationSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.score_label.sizePolicy().hasHeightForWidth())
        self.score_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.score_label.setFont(font)
        self.score_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.score_label.setWordWrap(True)
        self.score_label.setObjectName("score_label")
        self.horizontalLayout_2.addWidget(self.score_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, 50, 50, 50)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play_again_button = QtWidgets.QPushButton(TranslationSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.play_again_button.sizePolicy().hasHeightForWidth())
        self.play_again_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.play_again_button.setFont(font)
        self.play_again_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.play_again_button.setObjectName("play_again_button")
        self.horizontalLayout.addWidget(self.play_again_button)
        self.quit_button = QtWidgets.QPushButton(TranslationSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.quit_button.sizePolicy().hasHeightForWidth())
        self.quit_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout.addWidget(self.quit_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_layout = QtWidgets.QHBoxLayout()
        self.table_layout.setObjectName("table_layout")
        self.summary_table = QtWidgets.QTableView(TranslationSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.summary_table.sizePolicy().hasHeightForWidth())
        self.summary_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.summary_table.setFont(font)
        self.summary_table.setStyleSheet("QTableView {\n"
"    color: white;\n"
"    border: 2px solid #000000;\n"
"    padding: 10px;\n"
"    background-color: #FFE3BB;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: white;\n"
"    background-color: #FFD28F;\n"
"    border: 1px solid #555;\n"
"    height: 36px;\n"
"    width: 260px;\n"
"    font-weight: bold;\n"
"}")
        self.summary_table.setCornerButtonEnabled(False)
        self.summary_table.setObjectName("summary_table")
        self.table_layout.addWidget(self.summary_table)
        self.verticalLayout.addLayout(self.table_layout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TranslationSummary)
        QtCore.QMetaObject.connectSlotsByName(TranslationSummary)

    def retranslateUi(self, TranslationSummary):
        _translate = QtCore.QCoreApplication.translate
        TranslationSummary.setWindowTitle(_translate("TranslationSummary", "Summary"))
        self.score_label.setText(_translate("TranslationSummary", "Your Partial Score is:"))
        self.play_again_button.setText(_translate("TranslationSummary", "Play again!"))
        self.quit_button.setText(_translate("TranslationSummary", "Quit"))
