# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslationMode(object):
    def setupUi(self, TranslationMode):
        TranslationMode.setObjectName("TranslationMode")
        TranslationMode.resize(1033, 816)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 162, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        TranslationMode.setPalette(palette)
        TranslationMode.setStyleSheet("QWidget {\n"
"    background-color: #83A2FF;\n"
"    color: #FFFFFF;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(TranslationMode)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.question_label = QtWidgets.QLabel(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.question_label.sizePolicy().hasHeightForWidth())
        self.question_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.question_label.setFont(font)
        self.question_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.question_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_label.setWordWrap(True)
        self.question_label.setObjectName("question_label")
        self.verticalLayout_3.addWidget(self.question_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, -1, 50, 150)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, -1, 50, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_line_edit = QtWidgets.QLineEdit(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.input_line_edit.sizePolicy().hasHeightForWidth())
        self.input_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_line_edit.setFont(font)
        self.input_line_edit.setStyleSheet("border-radius: 20px; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #2E2E2E;\n"
"color: #FFD28F;\n"
"border: none;")
        self.input_line_edit.setObjectName("input_line_edit")
        self.verticalLayout_2.addWidget(self.input_line_edit)
        self.stacked_buttons = QtWidgets.QStackedWidget(TranslationMode)
        self.stacked_buttons.setStyleSheet("")
        self.stacked_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stacked_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stacked_buttons.setLineWidth(0)
        self.stacked_buttons.setObjectName("stacked_buttons")
        self.check_page = QtWidgets.QWidget()
        self.check_page.setObjectName("check_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.check_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_button = QtWidgets.QPushButton(self.check_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.check_button.sizePolicy().hasHeightForWidth())
        self.check_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.check_button.setFont(font)
        self.check_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        self.give_me_a_hint_button = QtWidgets.QPushButton(self.check_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.give_me_a_hint_button.sizePolicy().hasHeightForWidth())
        self.give_me_a_hint_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.give_me_a_hint_button.setFont(font)
        self.give_me_a_hint_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.give_me_a_hint_button.setObjectName("give_me_a_hint_button")
        self.horizontalLayout.addWidget(self.give_me_a_hint_button)
        self.stacked_buttons.addWidget(self.check_page)
        self.summary_page = QtWidgets.QWidget()
        self.summary_page.setObjectName("summary_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.summary_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_to_summary_button = QtWidgets.QPushButton(self.summary_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.go_to_summary_button.sizePolicy().hasHeightForWidth())
        self.go_to_summary_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.go_to_summary_button.setFont(font)
        self.go_to_summary_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.go_to_summary_button.setObjectName("go_to_summary_button")
        self.verticalLayout.addWidget(self.go_to_summary_button)
        self.stacked_buttons.addWidget(self.summary_page)
        self.verticalLayout_2.addWidget(self.stacked_buttons)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.character_combo_box = QtWidgets.QComboBox(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.character_combo_box.sizePolicy().hasHeightForWidth())
        self.character_combo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.character_combo_box.setFont(font)
        self.character_combo_box.setStyleSheet("text-align: center;\n"
"background-color: #2E2E2E;")
        self.character_combo_box.setMaxVisibleItems(7)
        self.character_combo_box.setObjectName("character_combo_box")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.character_combo_box.addItem("")
        self.horizontalLayout_2.addWidget(self.character_combo_box)
        self.add_character_button = QtWidgets.QPushButton(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.add_character_button.sizePolicy().hasHeightForWidth())
        self.add_character_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_character_button.setFont(font)
        self.add_character_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.add_character_button.setObjectName("add_character_button")
        self.horizontalLayout_2.addWidget(self.add_character_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.open_database_button = QtWidgets.QPushButton(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.open_database_button.sizePolicy().hasHeightForWidth())
        self.open_database_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_database_button.setFont(font)
        self.open_database_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.open_database_button.setObjectName("open_database_button")
        self.verticalLayout_2.addWidget(self.open_database_button)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.solution_label = QtWidgets.QLabel(TranslationMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.solution_label.sizePolicy().hasHeightForWidth())
        self.solution_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.solution_label.setFont(font)
        self.solution_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.solution_label.setText("")
        self.solution_label.setAlignment(QtCore.Qt.AlignCenter)
        self.solution_label.setWordWrap(True)
        self.solution_label.setObjectName("solution_label")
        self.horizontalLayout_3.addWidget(self.solution_label)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(TranslationMode)
        self.stacked_buttons.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TranslationMode)

    def retranslateUi(self, TranslationMode):
        _translate = QtCore.QCoreApplication.translate
        TranslationMode.setWindowTitle(_translate("TranslationMode", "Play Mode"))
        self.question_label.setText(_translate("TranslationMode", "The word to be translated is: "))
        self.check_button.setText(_translate("TranslationMode", "Check!"))
        self.give_me_a_hint_button.setText(_translate("TranslationMode", "Give me \n"
"a hint"))
        self.go_to_summary_button.setText(_translate("TranslationMode", "Go to Summary"))
        self.character_combo_box.setItemText(0, _translate("TranslationMode", "ä"))
        self.character_combo_box.setItemText(1, _translate("TranslationMode", "Ä"))
        self.character_combo_box.setItemText(2, _translate("TranslationMode", "ü"))
        self.character_combo_box.setItemText(3, _translate("TranslationMode", "Ü"))
        self.character_combo_box.setItemText(4, _translate("TranslationMode", "ö"))
        self.character_combo_box.setItemText(5, _translate("TranslationMode", "Ö"))
        self.character_combo_box.setItemText(6, _translate("TranslationMode", "ß"))
        self.add_character_button.setText(_translate("TranslationMode", "Add"))
        self.open_database_button.setText(_translate("TranslationMode", "Open Database"))
