# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Database(object):
    def setupUi(self, Database):
        Database.setObjectName("Database")
        Database.resize(1000, 797)
        Database.setStyleSheet("QWidget {\n"
"    background-color: #83A2FF;\n"
"    color: #FFFFFF;\n"
"}")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Database)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(Database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.horizontalLayout_Legend = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Legend.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Legend.setSpacing(0)
        self.horizontalLayout_Legend.setObjectName("horizontalLayout_Legend")
        self.legend = QtWidgets.QTableWidget(Database)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.legend.setFont(font)
        self.legend.setStyleSheet("background-color: #FFE3BB;")
        self.legend.setObjectName("legend")
        self.legend.setColumnCount(2)
        self.legend.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.legend.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.legend.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.legend.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.legend.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.legend.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.legend.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 210, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.legend.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.legend.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.legend.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.legend.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 165, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.legend.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.legend.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.legend.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.legend.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(144, 238, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.legend.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.legend.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.legend.setItem(4, 1, item)
        self.legend.horizontalHeader().setDefaultSectionSize(67)
        self.legend.horizontalHeader().setHighlightSections(True)
        self.legend.horizontalHeader().setMinimumSectionSize(0)
        self.legend.verticalHeader().setVisible(False)
        self.legend.verticalHeader().setDefaultSectionSize(34)
        self.legend.verticalHeader().setMinimumSectionSize(0)
        self.horizontalLayout_Legend.addWidget(self.legend)
        self.horizontalLayout.addLayout(self.horizontalLayout_Legend)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.go_back_button = QtWidgets.QPushButton(Database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.go_back_button.sizePolicy().hasHeightForWidth())
        self.go_back_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.go_back_button.setFont(font)
        self.go_back_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.go_back_button.setObjectName("go_back_button")
        self.horizontalLayout_2.addWidget(self.go_back_button)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.summary_table = QtWidgets.QTableView(Database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.summary_table.sizePolicy().hasHeightForWidth())
        self.summary_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.summary_table.setFont(font)
        self.summary_table.setStyleSheet("QTableView {\n"
"     color: white;     /* Set text color for cells */\n"
"    border: 2px solid #000000; /* Border color and width */\n"
"    padding: 10px; /* Adjust padding as needed */\n"
"    background-color: #FFE3BB;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"     color: white;     /* Set text color for header */\n"
"     background-color: #FFD28F; /* Set background color for header */\n"
"     border: 1px solid #555; /* Set border for header */\n"
"    height: 36px;     /* Set height for each header */\n"
"    width: 260px;\n"
"    font-weight: bold;\n"
"}")
        self.summary_table.setCornerButtonEnabled(False)
        self.summary_table.setObjectName("summary_table")
        self.horizontalLayout_3.addWidget(self.summary_table)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(Database)
        QtCore.QMetaObject.connectSlotsByName(Database)

    def retranslateUi(self, Database):
        _translate = QtCore.QCoreApplication.translate
        Database.setWindowTitle(_translate("Database", "Database"))
        self.title_label.setText(_translate("Database", "Database"))
        item = self.legend.verticalHeaderItem(0)
        item.setText(_translate("Database", "Beginner"))
        item = self.legend.verticalHeaderItem(1)
        item.setText(_translate("Database", "New Row"))
        item = self.legend.verticalHeaderItem(2)
        item.setText(_translate("Database", "Advanced"))
        item = self.legend.verticalHeaderItem(3)
        item.setText(_translate("Database", "Expert"))
        item = self.legend.verticalHeaderItem(4)
        item.setText(_translate("Database", "Master"))
        item = self.legend.horizontalHeaderItem(0)
        item.setText(_translate("Database", "Level"))
        item = self.legend.horizontalHeaderItem(1)
        item.setText(_translate("Database", "Color"))
        __sortingEnabled = self.legend.isSortingEnabled()
        self.legend.setSortingEnabled(False)
        item = self.legend.item(0, 0)
        item.setText(_translate("Database", "Beginner"))
        item = self.legend.item(1, 0)
        item.setText(_translate("Database", "Intermediate"))
        item = self.legend.item(2, 0)
        item.setText(_translate("Database", "Advanced"))
        item = self.legend.item(3, 0)
        item.setText(_translate("Database", "Expert"))
        item = self.legend.item(4, 0)
        item.setText(_translate("Database", "Master"))
        self.legend.setSortingEnabled(__sortingEnabled)
        self.go_back_button.setText(_translate("Database", "Go back"))
