# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'article_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArticleMode(object):
    def setupUi(self, ArticleMode):
        ArticleMode.setObjectName("ArticleMode")
        ArticleMode.resize(981, 781)
        ArticleMode.setStyleSheet("QWidget {\n"
"    background-color: #83A2FF;\n"
"    color: #FFFFFF;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ArticleMode)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, 100, 50, 100)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(ArticleMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.stacked_buttons = QtWidgets.QStackedWidget(ArticleMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stacked_buttons.sizePolicy().hasHeightForWidth())
        self.stacked_buttons.setSizePolicy(sizePolicy)
        self.stacked_buttons.setObjectName("stacked_buttons")
        self.article_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.article_page.sizePolicy().hasHeightForWidth())
        self.article_page.setSizePolicy(sizePolicy)
        self.article_page.setObjectName("article_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.article_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(200, -1, 200, -1)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.der_button = QtWidgets.QPushButton(self.article_page)
        self.der_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.der_button.sizePolicy().hasHeightForWidth())
        self.der_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.der_button.setFont(font)
        self.der_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.der_button.setObjectName("der_button")
        self.horizontalLayout.addWidget(self.der_button)
        self.die_button = QtWidgets.QPushButton(self.article_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.die_button.sizePolicy().hasHeightForWidth())
        self.die_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.die_button.setFont(font)
        self.die_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.die_button.setObjectName("die_button")
        self.horizontalLayout.addWidget(self.die_button)
        self.das_button = QtWidgets.QPushButton(self.article_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.das_button.sizePolicy().hasHeightForWidth())
        self.das_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.das_button.setFont(font)
        self.das_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; /* Adjust the radius as needed */\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.das_button.setObjectName("das_button")
        self.horizontalLayout.addWidget(self.das_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.stacked_buttons.addWidget(self.article_page)
        self.summary_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.summary_page.sizePolicy().hasHeightForWidth())
        self.summary_page.setSizePolicy(sizePolicy)
        self.summary_page.setObjectName("summary_page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.summary_page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(350, -1, 350, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.go_to_summary_button = QtWidgets.QPushButton(self.summary_page)
        self.go_to_summary_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.go_to_summary_button.sizePolicy().hasHeightForWidth())
        self.go_to_summary_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.go_to_summary_button.setFont(font)
        self.go_to_summary_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.go_to_summary_button.setObjectName("go_to_summary_button")
        self.horizontalLayout_2.addWidget(self.go_to_summary_button)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.stacked_buttons.addWidget(self.summary_page)
        self.verticalLayout.addWidget(self.stacked_buttons)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(350, -1, 350, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.open_database_button = QtWidgets.QPushButton(ArticleMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.open_database_button.sizePolicy().hasHeightForWidth())
        self.open_database_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_database_button.setFont(font)
        self.open_database_button.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #FFE3BB;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFD28F;\n"
"    }\n"
"QPushButton:pressed {\n"
"    background-color: #B4BDFF;\n"
"}")
        self.open_database_button.setObjectName("open_database_button")
        self.horizontalLayout_6.addWidget(self.open_database_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.comparison_result_label = QtWidgets.QLabel(ArticleMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comparison_result_label.sizePolicy().hasHeightForWidth())
        self.comparison_result_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comparison_result_label.setFont(font)
        self.comparison_result_label.setStyleSheet("border-radius: 50%; /* Makes the label circular */\n"
"border: 2px solid #000000; /* Border color and width */\n"
"padding: 10px; /* Adjust padding as needed */\n"
"background-color: #83A2FF;\n"
"color: #FFD28F;\n"
"border: none;\n"
"")
        self.comparison_result_label.setText("")
        self.comparison_result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comparison_result_label.setObjectName("comparison_result_label")
        self.verticalLayout.addWidget(self.comparison_result_label)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ArticleMode)
        self.stacked_buttons.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ArticleMode)

    def retranslateUi(self, ArticleMode):
        _translate = QtCore.QCoreApplication.translate
        ArticleMode.setWindowTitle(_translate("ArticleMode", "Article Mode"))
        self.title_label.setText(_translate("ArticleMode", "The word is:"))
        self.der_button.setText(_translate("ArticleMode", "Der"))
        self.die_button.setText(_translate("ArticleMode", "Die"))
        self.das_button.setText(_translate("ArticleMode", "Das"))
        self.go_to_summary_button.setText(_translate("ArticleMode", "Go to Summary"))
        self.open_database_button.setText(_translate("ArticleMode", "Open Database"))
